---
- name: SSH server installation
  apt:
    name: openssh-server
    state: latest
  become: yes

- name: SSH server is running
  systemd:
    name: ssh.service
    enabled: yes
    state: started
  become: yes
