username: platserv
groupname: platserv
home_dir: /home/{{ username }}
vpn_username: "{{ vault_platserv_vpn_username }}"
vpn_password: "{{ vault_platserv_vpn_password }}"
os_username: platserv
os_password_hash: "$1$3Zdze7Vx$yAFGerz.udprXLpTPEV7L0"
