---
- name: Copy html file to home directory
  copy:
    src: files/countdown.html
    dest: "{{ home_dir }}"

- name: LXDE to stop the display going to sleep
  copy:
    src: files/autostart
    dest: "{{ home_dir }}/.config/lxsession/LXDE-pi/autostart"

- name: Copy standup shell scripts to home directory
  copy:
    src: "files/{{ item }}"
    dest: "{{ home_dir }}/{{ item }}"
  with_items:
    - cleanup-after-standup.sh
    - countdown-to-standup.sh
    - prepare-for-standup.sh

- name: Crontab entry for countdown to standup
  cron:
    name: "countdown to standup"
    minute: "10"
    hour: "10"
    job: "/home/pi/countdown-to-standup.sh"

- name: Crontab entry for prepare for standup
  cron:
    name: "prepare for standup"
    minute: "15"
    hour: "10"
    job: "/home/pi/prepare-for-standup.sh"

- name: Crontab entry for clean up after standup
  cron:
    name: "clean up after standup"
    minute: "30"
    hour: "10"
    job: "/home/pi/cleanup-after-standup.sh"
