---
- name: Copy html file to home directory
  copy:
    src: files/countdown.html
    dest: "{{ home_dir }}"

- name: Upload cleanup after standup
  template:
    src: "templates/{{ item.src_template }}"
    dest: "{{ home_dir }}/{{ item.destination }}"
    mode: u=rx,g=rx,o=rx
  loop:
    - { src_template: 'cleanup-after-standup.sh.j2', destination: 'cleanup-after-standup.sh' }
    - { src_template: 'countdown-to-standup.sh.j2', destination: 'countdown-to-standup.sh' }
    - { src_template: 'prepare-for-standup.sh.j2', destination: 'prepare-for-standup.sh' }

- name: Crontab entry for countdown to standup
  cron:
    name: "countdown to standup"
    weekday: "mon-fri"
    minute: "10"
    hour: "10"
    job: "/home/pi/countdown-to-standup.sh"

- name: Crontab entry for prepare for standup
  cron:
    name: "prepare for standup"
    weekday: "mon-fri"
    minute: "15"
    hour: "10"
    job: "/home/pi/prepare-for-standup.sh"

- name: Crontab entry for clean up after standup
  cron:
    name: "clean up after standup"
    weekday: "mon-fri"
    minute: "30"
    hour: "10"
    job: "/home/pi/cleanup-after-standup.sh"

- name: Install Firefox browser
  apt:
    name: "{{ firefox }}"
    state: latest
  become: yes
