- name: OpenVPN client setup
  copy:
    src: files/aws-hmrc-vpn.ovpn
    dest: /etc/openvpn/client/aws-hmrc-vpn.conf
  become: yes

- name: OpenVPN client credentials
  template:
    src: templates/auth.txt.j2
    dest: /etc/openvpn/client/auth.txt
  become: yes

- name: OpenVPN client connection at startup
  systemd:
    name: openvpn-client@aws-hmrc-vpn.service
    enabled: yes
    state: started
  become: yes
