---
- name: OpenVPN installation
  apt:
    name: openvpn
    state: latest
  become: yes

- name: OpenVPN client setup
  copy:
    src: "files/{{ vpn_conf }}"
    dest: /etc/openvpn/client/aws-hmrc-vpn.conf
  become: yes

- name: OpenVPN client credentials
  template:
    src: templates/auth.txt.j2
    dest: /etc/openvpn/client/auth.txt
  become: yes

- name: OpenVPN client connection at startup
  systemd:
    name: openvpn-client@aws-hmrc-vpn.service
    enabled: yes
    state: started
  become: yes
